### ISSUE TITLE
Dose not work

### ISSUE THREAD

**Issue by pd-Shah** [dezhin/pygdal#28]
this dose not work:
```
pd@asghar:~$ sudo apt-get install libgdal1-dev
[sudo] password for pd: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgdal1-dev is already the newest version (1.11.3+dfsg-3build2).
The following packages were automatically installed and are no longer required:
  libcrypto++-dev libcrypto++9v5 libgstreamer-plugins-base0.10-0 libgstreamer0.10-0 linux-headers-4.8.0-36 linux-headers-4.8.0-36-generic linux-headers-4.8.0-46 linux-headers-4.8.0-46-generic
  linux-headers-4.8.0-49 linux-headers-4.8.0-49-generic linux-headers-4.8.0-51 linux-headers-4.8.0-51-generic linux-headers-4.8.0-53 linux-headers-4.8.0-53-generic linux-headers-4.8.0-54
  linux-headers-4.8.0-54-generic linux-headers-4.8.0-56 linux-headers-4.8.0-56-generic linux-headers-4.8.0-58 linux-headers-4.8.0-58-generic linux-image-4.8.0-36-generic linux-image-4.8.0-46-generic
  linux-image-4.8.0-49-generic linux-image-4.8.0-51-generic linux-image-4.8.0-53-generic linux-image-4.8.0-54-generic linux-image-4.8.0-56-generic linux-image-4.8.0-58-generic
  linux-image-extra-4.8.0-36-generic linux-image-extra-4.8.0-46-generic linux-image-extra-4.8.0-49-generic linux-image-extra-4.8.0-51-generic linux-image-extra-4.8.0-53-generic
  linux-image-extra-4.8.0-54-generic linux-image-extra-4.8.0-56-generic linux-image-extra-4.8.0-58-generic python-gobject python-gst0.10 python-libxml2 snap-confine
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
pd@asghar:~$ gdal-config --version
2.1.3
pd@asghar:~$ git clone git@github.com:dezhin/pygdal.git
Cloning into 'pygdal'...
remote: Counting objects: 380, done.
remote: Total 380 (delta 0), reused 0 (delta 0), pack-reused 380
Receiving objects: 100% (380/380), 1.37 MiB | 207.00 KiB/s, done.
Resolving deltas: 100% (212/212), done.
Checking connectivity... done.
pd@asghar:~$ cd pygdal
pd@asghar:~/pygdal$ virtualenv --no-site-packages env
New python executable in /home/pd/pygdal/env/bin/python
Installing setuptools, pip, wheel...done.
pd@asghar:~/pygdal$  env/bin/pip install 2.1.3/
Processing ./2.1.3
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-wvuVIB-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-wvuVIB-build/


```

**Comment by drnextgis** [comment]
How about installing from PyPi?

```
env/bin/pip install pygdal
```

**Comment by pd-Shah** [comment]
dose not work too:
```

pd@asghar:~$ sudo apt-get install libgdal1-dev
[sudo] password for pd: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgdal1-dev is already the newest version (1.11.3+dfsg-3build2).
The following packages were automatically installed and are no longer required:
  libcrypto++-dev libcrypto++9v5 libgstreamer-plugins-base0.10-0 libgstreamer0.10-0 linux-headers-4.8.0-36 linux-headers-4.8.0-36-generic linux-headers-4.8.0-46 linux-headers-4.8.0-46-generic
  linux-headers-4.8.0-49 linux-headers-4.8.0-49-generic linux-headers-4.8.0-51 linux-headers-4.8.0-51-generic linux-headers-4.8.0-53 linux-headers-4.8.0-53-generic linux-headers-4.8.0-54
  linux-headers-4.8.0-54-generic linux-headers-4.8.0-56 linux-headers-4.8.0-56-generic linux-headers-4.8.0-58 linux-headers-4.8.0-58-generic linux-image-4.8.0-36-generic linux-image-4.8.0-46-generic
  linux-image-4.8.0-49-generic linux-image-4.8.0-51-generic linux-image-4.8.0-53-generic linux-image-4.8.0-54-generic linux-image-4.8.0-56-generic linux-image-4.8.0-58-generic
  linux-image-extra-4.8.0-36-generic linux-image-extra-4.8.0-46-generic linux-image-extra-4.8.0-49-generic linux-image-extra-4.8.0-51-generic linux-image-extra-4.8.0-53-generic
  linux-image-extra-4.8.0-54-generic linux-image-extra-4.8.0-56-generic linux-image-extra-4.8.0-58-generic python-gobject python-gst0.10 python-libxml2 snap-confine
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
pd@asghar:~$ gdal-config --version
2.1.3
pd@asghar:~$  virtualenv --no-site-packages env
New python executable in /home/pd/env/bin/python
Installing setuptools, pip, wheel...done.
pd@asghar:~$ env/bin/pip install pygdal
Collecting pygdal
  Downloading pygdal-2.2.0.3.tar.gz (427kB)
    100% |████████████████████████████████| 430kB 85kB/s 




Collecting numpy>=1.0.0 (from pygdal)
  Using cached numpy-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl
Building wheels for collected packages: pygdal
  Running setup.py bdist_wheel for pygdal ... error
  Complete output from command /home/pd/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eXOKXh/pygdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpHQt_6zpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gdal.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gdalnumeric.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/ogr.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gdal_array.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/__init__.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/osr.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gnm.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gdalconst.py -> build/lib.linux-x86_64-2.7/osgeo
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-eXOKXh/pygdal/setup.py", line 173, in <module>
      cmdclass=dict(build_ext=gdal_ext),
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/pd/env/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-eXOKXh/pygdal/setup.py", line 41, in run
      inst_gdal_version, GDAL_VERSION))
  __main__.GDALConfigError: Version mismatch 2.1.3 != 2.2.0
  
  ----------------------------------------
  Failed building wheel for pygdal
  Running setup.py clean for pygdal
Failed to build pygdal
Installing collected packages: numpy, pygdal
  Running setup.py install for pygdal ... error
    Complete output from command /home/pd/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eXOKXh/pygdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mmZJPk-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pd/env/include/site/python2.7/pygdal:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/osgeo
    copying osgeo/gdal.py -> build/lib.linux-x86_64-2.7/osgeo
    copying osgeo/gdalnumeric.py -> build/lib.linux-x86_64-2.7/osgeo
    copying osgeo/ogr.py -> build/lib.linux-x86_64-2.7/osgeo
    copying osgeo/gdal_array.py -> build/lib.linux-x86_64-2.7/osgeo
    copying osgeo/__init__.py -> build/lib.linux-x86_64-2.7/osgeo
    copying osgeo/osr.py -> build/lib.linux-x86_64-2.7/osgeo
    copying osgeo/gnm.py -> build/lib.linux-x86_64-2.7/osgeo
    copying osgeo/gdalconst.py -> build/lib.linux-x86_64-2.7/osgeo
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-eXOKXh/pygdal/setup.py", line 173, in <module>
        cmdclass=dict(build_ext=gdal_ext),
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/pd/env/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-eXOKXh/pygdal/setup.py", line 41, in run
        inst_gdal_version, GDAL_VERSION))
    __main__.GDALConfigError: Version mismatch 2.1.3 != 2.2.0
    
    ----------------------------------------
Command "/home/pd/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eXOKXh/pygdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mmZJPk-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pd/env/include/site/python2.7/pygdal" failed with error code 1 in /tmp/pip-build-eXOKXh/pygdal/

```

**Comment by pd-Shah** [comment]
this is due to python version. it work fine on python 2:
```
```
pd@asghar:~/test$ gdal-config --version
2.1.3
pd@asghar:~/test$ bin/pip install pygdal2.1.3
Collecting pygdal2.1.3
  Could not find a version that satisfies the requirement pygdal2.1.3 (from versions: )
No matching distribution found for pygdal2.1.3
pd@asghar:~/test$ bin/pip install pygdal==2.1.3
Collecting pygdal==2.1.3
  Could not find a version that satisfies the requirement pygdal==2.1.3 (from versions: 1.8.1.0, 1.8.1.1, 1.8.1.2, 1.8.1.3, 1.9.2.0, 1.9.2.1, 1.9.2.3, 1.10.0.0, 1.10.0.1, 1.10.0.3, 1.10.1.0, 1.10.1.1, 1.10.1.3, 1.11.0.0, 1.11.0.1, 1.11.0.3, 1.11.1.0, 1.11.1.1, 1.11.1.3, 1.11.2.1, 1.11.2.3, 1.11.3.3, 1.11.4.3, 1.11.5.3, 2.0.0.3, 2.0.1.3, 2.0.2.3, 2.0.3.3, 2.1.0.3, 2.1.1.3, 2.1.2.3, 2.1.3.3, 2.2.0.3)
No matching distribution found for pygdal==2.1.3
pd@asghar:~/test$ bin/pip install pygdal==2.1.3.3
Collecting pygdal==2.1.3.3
  Downloading pygdal-2.1.3.3.tar.gz (407kB)
    100% |████████████████████████████████| 409kB 327kB/s 


Collecting numpy>=1.0.0 (from pygdal==2.1.3.3)
  Using cached numpy-1.13.1-cp35-cp35m-manylinux1_x86_64.whl
Building wheels for collected packages: pygdal
  Running setup.py bdist_wheel for pygdal ... done
  Stored in directory: /home/pd/.cache/pip/wheels/a9/b4/f7/96093f274d4351e160b71692fc40359ac48d2775ae1bbbe030
Successfully built pygdal
Installing collected packages: numpy, pygdal
Successfully installed numpy-1.13.1 pygdal-2.1.3.3
pd@asghar:~/test$ 
pd@asghar:~/test$ 
pd@asghar:~/test$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
>>> ``
```

but dose not work on python3:

```
pd@asghar:~$ virtualenv -p python3 test
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pd/test/bin/python3
Also creating executable in /home/pd/test/bin/python
Installing setuptools, pip, wheel...done.
(test) pd@asghar:~/test$ pip install pygdal==2.1.3.3
Requirement already satisfied: pygdal==2.1.3.3 in ./lib/python3.5/site-packages
Requirement already satisfied: numpy>=1.0.0 in ./lib/python3.5/site-packages (from pygdal==2.1.3.3)
(test) pd@asghar:~/test$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'gdal'

```

**Comment by pd-Shah** [comment]
yes, done .
installing gdal on python3 virtualenv:
```
pd@asghar:~$ virtualenv -p python3 test
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pd/test/bin/python3
Also creating executable in /home/pd/test/bin/python
Installing setuptools, pip, wheel...done.

pd@asghar:~$  gdal-config --version
2.1.3

pd@asghar:~$ test/bin/pip install pygdal==2.1.3
Collecting pygdal==2.1.3
  Could not find a version that satisfies the requirement pygdal==2.1.3 (from versions: 1.8.1.0, 1.8.1.1, 1.8.1.2, 1.8.1.3, 1.9.2.0, 1.9.2.1, 1.9.2.3, 1.10.0.0, 1.10.0.1, 1.10.0.3, 1.10.1.0, 1.10.1.1, 1.10.1.3, 1.11.0.0, 1.11.0.1, 1.11.0.3, 1.11.1.0, 1.11.1.1, 1.11.1.3, 1.11.2.1, 1.11.2.3, 1.11.3.3, 1.11.4.3, 1.11.5.3, 2.0.0.3, 2.0.1.3, 2.0.2.3, 2.0.3.3, 2.1.0.3, 2.1.1.3, 2.1.2.3, 2.1.3.3, 2.2.0.3)
No matching distribution found for pygdal==2.1.3

pd@asghar:~$ test/bin/pip install pygdal==2.1.3.3
Collecting pygdal==2.1.3.3
Collecting numpy>=1.0.0 (from pygdal==2.1.3.3)
  Using cached numpy-1.13.1-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: numpy, pygdal
Successfully installed numpy-1.13.1 pygdal-2.1.3.3

pd@asghar:~$ source test/bin/activate
(test) pd@asghar:~$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> 
```

**Comment by shaunstoltz** [comment]
ImportError: libncurses.so.6: cannot open shared object file: No such file or directory

**Comment by drnextgis** [comment]
@shaunstoltz can you filed a new issue with more details?
